platform :ios, '13.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!

target 'BFLoadingView_Example' do
  pod 'BFLoadingView', :path => '../'
end

# Set deployment target of pods to iOS 13 in order to silence XCode warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['SWIFT_VERSION'] = '5.1'
      end
    end
  end
end